---
title: "Political Dashboard"
output: flexdashboard::flex_dashboard

---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidytext)
library(twitteR)
library(tidytext)
library(dplyr)
library(ggplot2)
library(tidytext)
library(tidyverse)
library(anytime)
library(wordcloud)
library(knitr)
library(DT)
library(tidyr)
library(wordcloud2)
```


```{r prepping_data_for_word_clouds}
setwd("C:\\Users\\wgeit\\Repos\\STAT_5014_team_elephant_donkey")
# load data
trump_df <- readRDS("trump_df_raw.RDS")
biden_df <- readRDS("biden_df_raw.RDS")
debate1_df <- readRDS("debate1_df_raw.RDS")
debate2_df <- readRDS("debate2_df_raw.RDS")

# bring debates together
debate_df <- rbind(debate1_df, debate2_df)

# tokenize
tidy_trump_tweets <- trump_df %>% select(created_at, text) %>% unnest_tokens("word", text)
tidy_biden_tweets <- biden_df %>% select(timestamp, tweet) %>% unnest_tokens("word", tweet)
tidy_debate <- debate_df %>% select(text) %>% unnest_tokens("word", text)

# take out stop words
data("stop_words")
tidy_trump_tweets <- tidy_trump_tweets %>% anti_join(stop_words)
tidy_biden_tweets <- tidy_biden_tweets %>% anti_join(stop_words)
tidy_debate <- tidy_debate %>% anti_join(stop_words)

# excludes numbers
tidy_trump_tweets<-tidy_trump_tweets[-grep("\\b\\d+\\b", tidy_trump_tweets$word),]
tidy_biden_tweets<-tidy_biden_tweets[-grep("\\b\\d+\\b", tidy_biden_tweets$word),]
tidy_debate<-tidy_debate[-grep("\\b\\d+\\b", tidy_debate$word),]

# make a list of custom words to exclude
custom_stop_word <- as.data.frame(c("t.co", "https", "â", "iâ", "itâ", "weâ", "http", "amp", "rt", "ðÿ", "donâ", "ve", "youâ", "thatâ", "00", "theyâ", "heâ", "ll", "didnâ", "doesnâ", "01", "canâ", "thereâ", "whatâ", "hereâ", "10", "arenâ", "15", "35"))
colnames(custom_stop_word) <- c("word")

# make dataframe
tidy_debate <- as.data.frame(tidy_debate)
colnames(tidy_debate) <- c("word")

# take out custom words
tidy_trump_tweets <- tidy_trump_tweets %>% anti_join(custom_stop_word)
tidy_biden_tweets <- tidy_biden_tweets %>% anti_join(custom_stop_word)
tidy_debate <- tidy_debate %>% anti_join(custom_stop_word)

# get trump word count
trump_cnt <- tidy_trump_tweets %>%
  count(word) %>%
    arrange(desc(n))

# get biden word count
biden_cnt <- tidy_biden_tweets %>%
  count(word) %>%
    arrange(desc(n))

# get debate word count
debate_cnt <- tidy_debate %>%
  count(word) %>%
    arrange(desc(n))
```

Page 1
===================================== 
    
### Trump's Twitter Word Cloud
    
```{r}
# trump word cloud
wordcloud2(data = trump_cnt, size=1.6, color='red', shape = "circle")
```
    
### Biden's Twitter Word Cloud

```{r}
# biden word cloud
wordcloud2(data = biden_cnt, size=1.6, color='skyblue', shape = "circle")
```

### Debate Word Cloud

```{r}
# debate word cloud
wordcloud2(data = debate_cnt, size=1.6, color='random-dark')
```
   
Page 2
=====================================     

### Chart 1
    
```{r}

```

### Scraping 2016 & 2020 election results
# 2016
```{r}
library(rvest)
library(selectr)
library(xml2)
library(dplyr)

url <- 'https://www.politico.com/2016-election/results/map/president/'
webpage <- read_html(url)
title_html <- html_nodes(webpage, 'tbody') 
title <- html_text(title_html)

j<-strsplit(title, "\n")

list<-{}
for (i in 1:51)
{k<-unlist(j[i])
k<-k[k != ""]
k<-k[k != " "]
for (q in 1:8)
{if ((k[q]=="R Winner D. Trump")|(k[q]=="D Winner H. Clinton")|(k[q]=="D H. Clinton")|(k[q]=="R D. Trump"))
{list<-cbind(list,k[q],k[q+1],k[q+2])}
  }
 }

Matrix<- matrix(unlist(list), ncol = 6, byrow = TRUE)
Matrix
dat<-as.data.frame(Matrix)

for (i in (1:51))
{if (dat[i,1]=="D Winner H. Clinton")
  {a<-dat[i,4]
  b<-dat[i,5]
  c<-dat[i,6]
  d<-dat[i,1]
  e<-dat[i,2]
  f<-dat[i,3]
  dat[i,1]<-a
  dat[i,2]<-b
  dat[i,3]<-c
  dat[i,4]<-d
  dat[i,5]<-e
  dat[i,6]<-f}
}

#Not knowing why not work yet
#for (i in (1:51))
#{if (dat[i,1]=="D Winner H. Clinton")
#  inter<-data.frame(V1=character(),V2=character(),V3=character(),V4=character(),V5=character(),V6=character())
#  inter[1,1]<-dat[i,4]
#  inter[1,2]<-dat[i,5]
#  inter[1,3]<-dat[i,6]
#  inter[1,4]<-dat[i,1]
#  inter[1,5]<-dat[i,2]
#  inter[1,6]<-dat[i,3]
#  inter
#  dat[i,]<-inter[1,]
#}

library(downloader)
download("http://www.farinspace.com/wp-content/uploads/us_cities_and_states.zip",dest="us_cities_states.zip")
unzip("us_cities_states.zip", exdir="./")
library(data.table)
states <- fread(input = "./us_cities_and_states/states.sql",skip = 23,sep = "'", sep2 = ",", header = F, select = c(2,4))
colnames(states)<-c("fullname","states")
a<-order(states$fullname)
State<-data.frame(State=character())
for (i in 1:51)
{State[i,]<-states[a[i],1]}

dat<-cbind(State,dat)

df2<-dat[,c(1,6,7,3,4)]
colnames(df2)<-cbind('State','HillaryPercent','HillaryCounts','TrumpPercent','TrumpCounts')

df2[,3]<-as.numeric(gsub(",", "", df2[,3]))
df2[,5]<-as.numeric(gsub(",", "", df2[,5]))
df2[,2]<-as.numeric(sub("%","",df2[,2]))/100
df2[,4]<-as.numeric(sub("%","",df2[,4]))/100

df2
```
# 2020
```{r cars}
#install.packages('rvest')
#install.packages('selectr')
library(rvest)
library(selectr)
library(xml2)
library(dplyr)

url <- 'https://www.nbcnews.com/politics/2020-elections/president-results?icid=election_nav'
webpage <- read_html(url)
title_html <- html_nodes(webpage, 'tbody') 
#title_html1 <- html_nodes(webpage, 'tbody') %>% html_children()
title <- html_text(title_html)

j<-strsplit(title[1], " ")
j<-unlist(j)

j1<-j[532:541]
j2<-j1[c(2,3,5,6,10)]

j<-j[-122]
j[135]<-"North Carolina"
j<-j[-134]
j[132]<-'New Jersey'
j<-j[-131]
j[146]<-'North Dakota'
j<-j[-145]
j<-j[-142]
j[142]<-'North Carolina'
j[154]<-'North Dakota'
j<-j[-153]
j[178]<-'South Dakota'
j<-j[-177]
j[187]<-'South Dakota'
j<-j[-186]
j[233]<-'West Virginia'
j<-j[-232]
j[242]<-'West Virginia'
j<-j[-241]
j[255]<-'New Mexico'
j[265]<-'New Mexico'
j[302]<-'DC'
j[403]<-'New Hampshire'
j[393]<-'New Hampshire'
j[406]<-'New York'
j[416]<-'New York'
j[496]<-'American Samoa'
j[500]<-'American Samoa'
j<-j[-c(254,264,300,301,402,392,405,415,495,499)]
j[309]<-'DC'
j<-j[-c(307,308)]
j<-j[-c(490:509)]
j<-j[-c(485:488)]
j<-j[-485]
j<-j[-c(485:494)]
j[487]<-'South Carolina'
j[497]<-'South Carolina'
j<-j[-c(486,496,499:516)]
j<-j[-485]
j[541]<-'Rhode Island'
j[551]<-'Rhode Island'
j<-j[-c(540,550)]

q<-{}
for (i in 0:49)
{q<-cbind(q,j[2+i*11],j[3+i*11],j[5+i*11],j[6+i*11],j[10+i*11])}
q<-cbind(q,j2[1],j2[2],j2[3],j2[4],j2[5])

Matrix<- matrix(unlist(q), ncol = 5, byrow = TRUE)

df<-as.data.frame(Matrix)
colnames(df)<-c('Biden percent','Biden Counts','Trump percent','Trump Counts','State')
df2<-df[,c(5,1,2,3,4)]
df2

df2[,3]<-as.numeric(gsub(",", "", df2[,3]))
df2[,5]<-as.numeric(gsub(",", "", df2[,5]))
df2[,2]<-as.numeric(sub("%","",df2[,2]))/100
df2[,4]<-as.numeric(sub("%","",df2[,4]))/100

df2
```
    
### Trump's supporting rate over time

```{r}
df<-read.csv('fivethirtyeight.csv', header = TRUE, sep = ",")
df
Adults<-df[df$subgroup == 'Adults', ]
Allpolls<-df[df$subgroup == 'All polls', ]
Voters<-df[df$subgroup == 'Voters', ]
par(mfrow=c(2,3))

Adults$date<-as.Date(Adults$date)
df2 <- data.frame(Day=Adults$date,
                    ApprovePercet=Adults$approve_estimate,lwr=Adults$approve_lo,upr=Adults$approve_hi)
plot(ApprovePercet~Day,data=df2,ylim=range(c(df2$lwr,df2$upr)))
 #make polygon where coordinates start with lower limit and then upper limit in reverse order
with(df2,polygon(c(Day,rev(Day)),c(lwr,rev(upr)),col = "pink", border = FALSE))
matlines(df2[,1],df2[,-1],
          lwd=c(2,1,1),
          lty=1,
          col=c("red","pink",'pink'),
        )
title(main="Adults")

Allpolls$date<-as.Date(Allpolls$date)
df2 <- data.frame(Day=Allpolls$date,
                    ApprovePercet=Allpolls$approve_estimate,lwr=Allpolls$approve_lo,upr=Allpolls$approve_hi)
plot(ApprovePercet~Day,data=df2,ylim=range(c(df2$lwr,df2$upr)))
 #make polygon where coordinates start with lower limit and then upper limit in reverse order
with(df2,polygon(c(Day,rev(Day)),c(lwr,rev(upr)),col = "pink", border = FALSE))
matlines(df2[,1],df2[,-1],
          lwd=c(2,1,1),
          lty=1,
          col=c("red","pink",'pink'),
        )
title(main="All polls")

Voters$date<-as.Date(Voters$date)
df2 <- data.frame(Day=Voters$date,
                    ApprovePercet=Voters$approve_estimate,lwr=Voters$approve_lo,upr=Voters$approve_hi)
plot(ApprovePercet~Day,data=df2,ylim=range(c(df2$lwr,df2$upr)))
 #make polygon where coordinates start with lower limit and then upper limit in reverse order
with(df2,polygon(c(Day,rev(Day)),c(lwr,rev(upr)),col = "pink", border = FALSE))
matlines(df2[,1],df2[,-1],
          lwd=c(2,1,1),
          lty=1,
          col=c("red","pink",'pink'),
        )
title(main="Voters")

Adults$date<-as.Date(Adults$date)
df2 <- data.frame(Day=Adults$date,
                    DisapprovePercet=Adults$disapprove_estimate,lwr=Adults$disapprove_lo,upr=Adults$disapprove_hi)
plot(DisapprovePercet~Day,data=df2,ylim=range(c(df2$lwr,df2$upr)))
 #make polygon where coordinates start with lower limit and then upper limit in reverse order
with(df2,polygon(c(Day,rev(Day)),c(lwr,rev(upr)),col = "cadetblue1", border = FALSE))
matlines(df2[,1],df2[,-1],
          lwd=c(2,1,1),
          lty=1,
          col=c("blue","cadetblue1",'cadetblue1'),
        )
title(main="Adults")

Allpolls$date<-as.Date(Allpolls$date)
df2 <- data.frame(Day=Allpolls$date,
                    DisapprovePercet=Allpolls$disapprove_estimate,lwr=Allpolls$disapprove_lo,upr=Allpolls$disapprove_hi)
plot(DisapprovePercet~Day,data=df2,ylim=range(c(df2$lwr,df2$upr)))
 #make polygon where coordinates start with lower limit and then upper limit in reverse order
with(df2,polygon(c(Day,rev(Day)),c(lwr,rev(upr)),col = "cadetblue1", border = FALSE))
matlines(df2[,1],df2[,-1],
          lwd=c(2,1,1),
          lty=1,
          col=c("blue","cadetblue1",'cadetblue1'),
        )
title(main="All polls")

Voters$date<-as.Date(Voters$date)
df2 <- data.frame(Day=Voters$date,
                    DisapprovePercet=Voters$disapprove_estimate,lwr=Voters$disapprove_lo,upr=Voters$disapprove_hi)
plot(DisapprovePercet~Day,data=df2,ylim=range(c(df2$lwr,df2$upr)))
 #make polygon where coordinates start with lower limit and then upper limit in reverse order
with(df2,polygon(c(Day,rev(Day)),c(lwr,rev(upr)),col = "cadetblue1", border = FALSE))
matlines(df2[,1],df2[,-1],
          lwd=c(2,1,1),
          lty=1,
          col=c("blue","cadetblue1",'cadetblue1'),
        )
title(main="Voters")
```
```
